### ISSUE TITLE
Issue with using TOEFL ID in search

### ISSUE THREAD

**Issue by slstaples** [writecrow/crow_backend#13]
I just tried the following search: 
"talk about" with the filter TOEFL score 70-100
I got an error message.
I previously tried a related search (same phrase but TOEFL score 100-120). It took a while to get results but they did come through.

**Comment by markfullmer** [comment]
Thanks @slstaples . 

I just tried replicating that search -- see URL below -- and wasn't able to reproduce the error. I'll check the error logs to debug further, but if you can reproduce on your end & send along the URL, that will help.

https://crow.corporaproject.org/corpus?search=%22talk%20about%22&op=or&method=word&offset=0&toefl_total_min=70&toefl_total_max=100

**Comment by slstaples** [comment]
Thanks, Mark! It's definitely working now. I also tried a bunch of other one-word reporting verbs and it worked fine. So maybe it was a temporary issue with my internet service? I'm on wired internet on campus, but you never know! I'll let you know if I get it again.

**Comment by markfullmer** [comment]
No further reports of this problem. Closing issue.
