### ISSUE TITLE
Investigate updating version of simple_oauth

### ISSUE THREAD

**Issue by markfullmer** [writecrow/crow_backend#3]
## Description of task

https://www.drupal.org/project/simple_oauth

**Comment by markfullmer** [comment]
This was completed as part of the update to Drupal 9.

**Comment by cbdilger** [comment]
ooooooo tell me more do we have oauth now?

**Comment by markfullmer** [comment]
> ooooooo tell me more do we have oauth now?

We've been using OAuth protocol all along -- this was just an update to a library. If you're more referring to using OAuth for things like federated authentication (e.g., "Sign in with Google/Facebook"), we don't have that configured, but we could do that, if desired.

**Comment by cbdilger** [comment]
Thank you, sir. Maybe we should investigate that in the future. I onboarded Shelton for the web work he'll be doing this summer and that involved two new passwords (GitHub, Crow platform).
